apiVersion: v1
kind: Secret

metadata:
  name: barkly-api-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.api.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.api.datasource.password | quote }}