apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: barkly-postgres-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}