apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barkly-postgres-pvc
  namespace: barkly
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barkly-postgres
  namespace: barkly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barkly-postgres
  template:
    metadata:
      labels:
        app: barkly-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_DB
          value: barkly
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName:  barkly-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: barkly-postgres
  namespace: barkly
spec:
  selector:
    app: barkly-postgres
  ports:
  - port: 5432
    targetPort: 5432
